An error occured while running "{{ command.lockName }}" command (id: {{ command.id }}).

Exception: "{{ exception.message }}"
Code: {{ exception.code }}
File: {{ exception.file }}
Line: {{ exception.line }}
==========================

Trace:
{{ exception.traceAsString }}
